server.port: 7000
spring:
  rabbitmq:
    host: localhost
  cloud:
    stream:
      bindings:
        certificateOrderedChannel:
          destination: CREDS_EXCHANGE
    rabbit:
      bindings:
        certificateOrderedChannel:
          producer:
            routing-key-expression: "'creds.certificate.ordered'"

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
